### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by josht-dev** [Spalding004/fortunate_1_15#2]
The mod seems to crash immediately when used on a server. I loaded a minecraft 1.15.2 server with forge 31.2.30 and How Fortunate version 2.7 as the only mod. Here is a link to the crash log: https://pastebin.com/raw/X7EhwFYR

Also, I wasn't sure if you wanted issues here or on the curseforge page, so it is also posted there.

PS. Love the mod, wish I knew about it when I make other personal modpacks!

**Comment by Spalding004** [comment]
should be fixed in 2.7.1, releasing shortly.

**Comment by josht-dev** [comment]
The updated version (2.7.1) still crashes the server with it being the only mod loaded. The crash log does appear to be for a different reason though. Here is the log: https://pastebin.com/raw/HQGHbvGg

Was a different forge version required for the fix? Thanks.

**Comment by Spalding004** [comment]
Oops, my bad.  Made the change in the correct place now, I wasn't aware of the way forge was handling item colors and block colors server-side in 1.15/1.16.  Uploading a fix now, v2.8

**Comment by josht-dev** [comment]
It works on the server now. There is one issue I believe is unintended. I added silent mechanisms (v. 1.15.2-0.7.6+57) to test modded ores and the chunks for those are all the same color as well as the ingots. Here is a screenshot for the chunks.
![image](https://user-images.githubusercontent.com/49009098/87201835-a4a2e300-c2bc-11ea-856b-19f4ae1769f3.png)

**Comment by Spalding004** [comment]
urgh, if its not one thing it's another. I've been a little busy lately so I haven't had the opportunity to look into this yet.

**Comment by josht-dev** [comment]
Completely understandable. I appreciate you looking into it when you have time.

**Comment by Spalding004** [comment]
https://github.com/Spalding004/fortunate_1_15/releases/tag/v2.8.1

Fixed here. Just note that the ingot/chunk colors will not necessarily match the colors in that mod; I had to find a middle ground between allll the mods that add the same metals.
